FROM erlang:21-alpine

LABEL maintainer="jorge.franco@osoco.es"
LABEL Description="This image contains odocker application that interacts with your docker api"

COPY odocker /odocker
COPY version /version
